export enum DhcpOptionOrigin {
  GLOBAL_DHCP_CONFIG = 'GLOBAL_DHCP_CONFIG',
  IP_SPACE = 'IP_SPACE',
  ADDRESS_BLOCK = 'ADDRESS_BLOCK',
  SUBNET = 'SUBNET',
  RANGE = 'RANGE',
  FIXED_ADDRESS = 'FIXED_ADDRESS',
  OPTION_GROUP = 'OPTION_GROUP',
  CONFIG_PROFILE = 'CONFIG_PROFILE',
}
